# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = ImageSystem
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"../../../VTK-9.4.2/install/lib" \
    -lvtkCommonCore-9.4d \
    -lvtkCommonDataModel-9.4d \
    -lvtkCommonExecutionModel-9.4d \
    -lvtkCommonTransforms-9.4d \
    -lvtkCommonMath-9.4d \
    -lvtkCommonColor-9.4d \
    -lvtkCommonSystem-9.4d \
    -lvtkCommonMisc-9.4d \
    -lvtkRenderingCore-9.4d \
    -lvtkRenderingOpenGL2-9.4d \
    -lvtkRenderingFreeType-9.4d \
    -lvtkRenderingVolume-9.4d \
    -lvtkRenderingVolumeOpenGL2-9.4d \
    -lvtkRenderingImage-9.4d \
    -lvtkInteractionWidgets-9.4d \
    -lvtkInteractionStyle-9.4d \
    -lvtkInteractionImage-9.4d \
    -lvtkImagingCore-9.4d \
    -lvtkImagingColor-9.4d \
    -lvtkIOCore-9.4d \
    -lvtkIOImage-9.4d \
    -lvtkGUISupportQt-9.4d \
    -lvtkGUISupportQtQuick-9.4d \
    -lvtksys-9.4d \
    -lvtkglad-9.4d \
    -lvtkFiltersSources-9.4d \
    -lvtkFiltersExtraction-9.4d \
    -lvtkFiltersCore-9.4d \
    -lvtkFiltersModeling-9.4d \
    -lvtkFiltersGeometry-9.4d
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
HEADERS += ./CustomInteractorStyle.h \
    ./CustomVTKItem.h
SOURCES += ./main.cpp \
    ./CustomInteractorStyle.cpp \
    ./CustomVTKItem.cpp
RESOURCES += qml.qrc
